// 🔧 LegalDocModal.jsx - In-app legal document viewer (iOS Safari friendly)
import React from 'react';
import { X, ArrowLeft } from 'lucide-react';

const LegalDocModal = ({
  isOpen,
  onClose,
  docType = 'terms',
  uiLanguage = 'cs'
}) => {

  const getDocContent = (type) => {
    switch (type) {
      case 'terms':
        return {
          title: 'Terms of Service',
          lastUpdated: 'September 14, 2025',
          content: `
            <div class="important">
              <p><strong>Important:</strong> By using Omnia One AI, you agree to these terms. Please read them carefully before using our service.</p>
            </div>

            <h2>1. Acceptance of Terms</h2>
            <p>By accessing and using Omnia One AI ("the Service"), you accept and agree to be bound by the terms and provision of this agreement.</p>

            <h2>2. Description of Service</h2>
            <p>Omnia One AI is an artificial intelligence chat application that provides:</p>
            <ul>
              <li>AI-powered conversations using multiple models (Claude, GPT-4, Gemini)</li>
              <li>Voice interaction capabilities</li>
              <li>Document processing and analysis</li>
              <li>Multi-language support</li>
              <li>File upload and processing features</li>
            </ul>

            <h2>3. AI Service Limitations</h2>
            <div class="note">
              <p><strong>AI Disclaimer:</strong> Our AI responses are generated by machine learning models and may contain inaccuracies, biases, or outdated information. Always verify important information from authoritative sources.</p>
            </div>

            <p>You acknowledge that:</p>
            <ul>
              <li>AI responses are not professional advice (medical, legal, financial, etc.)</li>
              <li>The service may occasionally generate incorrect or inappropriate content</li>
              <li>We do not guarantee the accuracy or completeness of AI responses</li>
              <li>You use AI-generated content at your own risk</li>
            </ul>

            <h2>4. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul>
              <li>Use the service lawfully and responsibly</li>
              <li>Not attempt to exploit, harm, or reverse-engineer the service</li>
              <li>Not share harmful, illegal, or inappropriate content</li>
              <li>Respect intellectual property rights</li>
              <li>Not use the service for automated/bulk requests without permission</li>
            </ul>

            <h2>5. Data and Privacy</h2>
            <p>Your privacy is important to us:</p>
            <ul>
              <li>Chat conversations are stored locally in your browser</li>
              <li>We process your data as described in our Privacy Policy</li>
              <li>Files you upload are processed for AI analysis</li>
              <li>We implement security measures to protect your data</li>
            </ul>

            <h2>6. Prohibited Uses</h2>
            <p>You may NOT use Omnia One AI to:</p>
            <ul>
              <li>Generate harmful, illegal, or malicious content</li>
              <li>Harass, threaten, or harm others</li>
              <li>Violate any laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Attempt to circumvent service limitations</li>
              <li>Create or distribute malware, viruses, or harmful code</li>
            </ul>

            <h2>7. Service Availability</h2>
            <p>We strive to provide reliable service but cannot guarantee:</p>
            <ul>
              <li>100% uptime or availability</li>
              <li>Uninterrupted access to all features</li>
              <li>That the service will be error-free</li>
            </ul>

            <h2>8. Intellectual Property</h2>
            <p>The Omnia One AI service, including its design, code, and features, is owned by us and protected by intellectual property laws. You retain ownership of content you create, but grant us permission to process it for service delivery.</p>

            <h2>9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.</p>

            <h2>10. Account Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time through the settings.</p>

            <h2>11. Changes to Terms</h2>
            <p>We may update these terms periodically. Significant changes will be communicated through the service. Continued use constitutes acceptance of updated terms.</p>

            <h2>12. Governing Law</h2>
            <p>These terms are governed by applicable laws. Any disputes will be resolved through appropriate legal channels.</p>

            <h2>13. Contact Information</h2>
            <p>If you have questions about these Terms of Service, please contact us through the support channels available in the application.</p>

            <div class="note">
              <p><strong>Remember:</strong> These terms are designed to ensure a safe and positive experience for all users. By using Omnia One AI responsibly, you help us maintain a great service for everyone.</p>
            </div>
          `
        };

      case 'privacy':
        return {
          title: 'Privacy Policy',
          lastUpdated: 'September 14, 2025',
          content: `
            <div class="important">
              <p><strong>Important:</strong> This privacy policy explains how we collect, use, and protect your information when using Omnia One AI.</p>
            </div>

            <h2>Coming Soon</h2>
            <p>Privacy Policy content will be available soon. For now, please refer to our third-party AI providers' privacy policies:</p>
            <ul>
              <li><a href="https://www.anthropic.com/privacy" target="_blank">Anthropic Privacy Policy</a></li>
              <li><a href="https://openai.com/privacy/" target="_blank">OpenAI Privacy Policy</a></li>
              <li><a href="https://policies.google.com/privacy" target="_blank">Google Privacy Policy</a></li>
            </ul>
          `
        };

      case 'anthropic-privacy':
        return {
          title: 'Anthropic Privacy Policy',
          lastUpdated: 'Referenced from Anthropic.com',
          content: `
            <div class="note">
              <p><strong>Note:</strong> This is a summary of Anthropic's privacy practices. For the complete and most up-to-date policy, visit <a href="https://www.anthropic.com/privacy" target="_blank">anthropic.com/privacy</a></p>
            </div>

            <h2>How Anthropic Processes Your Data</h2>
            <p>When you use Omnia with Anthropic Claude, your messages are sent to Anthropic's servers for processing. Key points:</p>

            <ul>
              <li>Anthropic processes your conversations to generate AI responses</li>
              <li>They may use conversations for model training and improvement</li>
              <li>Data is handled according to their privacy policy and security practices</li>
              <li>You can review their full privacy policy for detailed information</li>
            </ul>

            <h2>Your Rights</h2>
            <p>Regarding data processed by Anthropic, you may have rights including:</p>
            <ul>
              <li>Access to your personal data</li>
              <li>Correction of inaccurate data</li>
              <li>Deletion requests (subject to their policies)</li>
              <li>Data portability in some cases</li>
            </ul>

            <h2>Contact Anthropic</h2>
            <p>For questions about how Anthropic processes your data, contact them directly through their official channels at anthropic.com</p>

            <div class="important">
              <p><strong>Important:</strong> This summary is for informational purposes only. Anthropic's actual privacy policy at anthropic.com/privacy takes precedence and contains the authoritative terms.</p>
            </div>
          `
        };

      case 'openai-privacy':
        return {
          title: 'OpenAI Privacy Policy',
          lastUpdated: 'Referenced from OpenAI.com',
          content: `
            <div class="note">
              <p><strong>Note:</strong> This is a summary of OpenAI's privacy practices. For the complete and most up-to-date policy, visit <a href="https://openai.com/privacy/" target="_blank">openai.com/privacy</a></p>
            </div>

            <h2>How OpenAI Processes Your Data</h2>
            <p>When you use Omnia with OpenAI GPT models, your messages are sent to OpenAI's servers. Key points:</p>

            <ul>
              <li>OpenAI processes your conversations to provide AI responses</li>
              <li>They implement security measures to protect your data</li>
              <li>Data handling is governed by their privacy policy</li>
              <li>They may use data for service improvement and safety purposes</li>
            </ul>

            <h2>Data Retention</h2>
            <p>OpenAI has specific policies regarding how long they retain conversation data:</p>
            <ul>
              <li>API usage data may be retained for security and abuse prevention</li>
              <li>Specific retention periods are outlined in their privacy policy</li>
              <li>You can find current retention policies at openai.com/privacy</li>
            </ul>

            <h2>Contact OpenAI</h2>
            <p>For questions about how OpenAI processes your data, contact them directly through their support channels.</p>

            <div class="important">
              <p><strong>Important:</strong> This summary is for informational purposes only. OpenAI's actual privacy policy at openai.com/privacy contains the authoritative and complete terms.</p>
            </div>
          `
        };

      case 'google-privacy':
        return {
          title: 'Google Privacy Policy',
          lastUpdated: 'Referenced from Google Policies',
          content: `
            <div class="note">
              <p><strong>Note:</strong> This is a summary of Google's privacy practices. For the complete policy, visit <a href="https://policies.google.com/privacy" target="_blank">policies.google.com/privacy</a></p>
            </div>

            <h2>How Google Processes Your Data</h2>
            <p>When you use Omnia with Google Gemini, your data is processed by Google. Key aspects:</p>

            <ul>
              <li>Google processes conversations to provide AI responses</li>
              <li>Data handling follows Google's comprehensive privacy policy</li>
              <li>They implement various security and privacy protections</li>
              <li>Processing may include analysis for service improvement</li>
            </ul>

            <h2>Google's Privacy Principles</h2>
            <p>Google operates under established privacy principles:</p>
            <ul>
              <li>Transparency about data collection and use</li>
              <li>User control over privacy settings</li>
              <li>Strong security measures</li>
              <li>Compliance with applicable privacy laws</li>
            </ul>

            <h2>Your Privacy Controls</h2>
            <p>Google provides various tools to manage your privacy:</p>
            <ul>
              <li>Privacy settings and controls</li>
              <li>Data export and portability options</li>
              <li>Account activity management</li>
            </ul>

            <div class="important">
              <p><strong>Important:</strong> This summary is for informational purposes only. Google's complete privacy policy at policies.google.com/privacy contains the authoritative terms.</p>
            </div>
          `
        };

      case 'elevenlabs-privacy':
        return {
          title: 'ElevenLabs Privacy Policy',
          lastUpdated: 'Referenced from ElevenLabs.io',
          content: `
            <div class="note">
              <p><strong>Note:</strong> This is a summary of ElevenLabs' privacy practices. For the complete policy, visit <a href="https://elevenlabs.io/privacy" target="_blank">elevenlabs.io/privacy</a></p>
            </div>

            <h2>How ElevenLabs Processes Your Data</h2>
            <p>When you use Omnia's voice features powered by ElevenLabs:</p>

            <ul>
              <li>Voice data is processed to provide text-to-speech and speech-to-text services</li>
              <li>Audio processing follows their privacy and security practices</li>
              <li>Data handling is governed by their privacy policy</li>
              <li>They implement measures to protect voice data privacy</li>
            </ul>

            <h2>Voice Data Processing</h2>
            <p>ElevenLabs specializes in voice AI technology:</p>
            <ul>
              <li>Voice synthesis and recognition processing</li>
              <li>Quality improvement and model training</li>
              <li>Security measures for audio data</li>
              <li>Compliance with privacy regulations</li>
            </ul>

            <h2>Contact ElevenLabs</h2>
            <p>For specific questions about voice data processing, contact ElevenLabs directly through their official support channels.</p>

            <div class="important">
              <p><strong>Important:</strong> This summary is for informational purposes only. ElevenLabs' actual privacy policy at elevenlabs.io/privacy contains the complete and authoritative terms.</p>
            </div>
          `
        };

      default:
        return {
          title: 'Legal Document',
          lastUpdated: 'September 14, 2025',
          content: '<p>Document content coming soon...</p>'
        };
    }
  };

  const docData = getDocContent(docType);

  if (!isOpen) return null;

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        zIndex: 99999, // Higher than AboutModal
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        animation: 'fadeIn 0.2s ease'
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      {/* MODAL CONTENT - FULLSCREEN */}
      <div
        style={{
          width: '100vw',
          height: '100vh',
          background: 'linear-gradient(135deg, rgba(0, 4, 40, 0.95), rgba(0, 78, 146, 0.90))',
          backdropFilter: 'blur(20px)',
          WebkitBackdropFilter: 'blur(20px)',
          border: '1px solid rgba(255, 255, 255, 0.1)',
          display: 'flex',
          flexDirection: 'column',
          animation: 'slideUp 0.3s ease-out',
          position: 'relative'
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* HEADER - Fixed Top (like UserSettingsModal) */}
        <div style={{
          padding: '2rem 2rem 1rem',
          borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          position: 'relative'
        }}>
          {/* Close Button */}
          <button
            onClick={onClose}
            style={{
              position: 'absolute',
              top: '2rem',
              right: '2rem',
              background: 'transparent',
              border: 'none',
              color: 'rgba(255, 255, 255, 0.7)',
              cursor: 'pointer',
              outline: 'none',
              WebkitTapHighlightColor: 'transparent !important',
              WebkitFocusRingColor: 'transparent !important',
              boxShadow: 'none !important',
              userSelect: 'none',
              WebkitUserSelect: 'none',
              padding: '0.25rem',
              borderRadius: '6px',
              fontSize: '1.25rem',
              lineHeight: 1,
              transition: 'all 0.2s ease',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}
            onMouseEnter={(e) => {
              e.target.style.backgroundColor = 'rgba(255, 255, 255, 0.1)';
              e.target.style.color = 'rgba(255, 255, 255, 0.9)';
            }}
            onMouseLeave={(e) => {
              e.target.style.backgroundColor = 'transparent';
              e.target.style.color = 'rgba(255, 255, 255, 0.7)';
            }}
          >
            <X size={20} />
          </button>

          {/* Title */}
          <h1 style={{
            color: 'white',
            fontSize: '1.5rem',
            fontWeight: 'bold',
            margin: '0 0 0.5rem 0'
          }}>
            {docData.title}
          </h1>

          {/* Last Updated */}
          <div style={{
            color: 'rgba(255, 255, 255, 0.6)',
            fontSize: '0.9rem'
          }}>
            Last updated: {docData.lastUpdated}
          </div>
        </div>

        {/* SCROLLABLE CONTENT (like UserSettingsModal) */}
        <div style={{
          flex: 1,
          padding: '1.5rem 2rem',
          overflowY: 'auto'
        }}>
          <div style={{
            maxWidth: '800px',
            margin: '0 auto',
            fontSize: '0.9rem',
            lineHeight: '1.6',
            color: 'rgba(255, 255, 255, 0.9)'
          }}>
            <style dangerouslySetInnerHTML={{
              __html: `
                .important {
                  background: rgba(220, 38, 38, 0.1);
                  border: 1px solid rgba(220, 38, 38, 0.3);
                  border-radius: 8px;
                  padding: 1rem;
                  margin: 1.5rem 0;
                }

                .note {
                  background: rgba(59, 130, 246, 0.1);
                  border: 1px solid rgba(59, 130, 246, 0.3);
                  border-radius: 8px;
                  padding: 1rem;
                  margin: 1.5rem 0;
                }

                h2 {
                  font-size: 1.3rem;
                  font-weight: 600;
                  margin: 2rem 0 1rem 0;
                  color: #00d4ff;
                }

                h3 {
                  font-size: 1.1rem;
                  font-weight: 500;
                  margin: 1.5rem 0 0.5rem 0;
                  color: #8c52ff;
                }

                p {
                  margin-bottom: 1rem;
                  color: rgba(255, 255, 255, 0.9);
                }

                ul, ol {
                  margin: 1rem 0 1rem 2rem;
                }

                li {
                  margin-bottom: 0.5rem;
                  color: rgba(255, 255, 255, 0.9);
                }

                a {
                  color: #00d4ff;
                  text-decoration: none;
                  border-bottom: 1px solid transparent;
                  transition: border-color 0.2s ease;
                }

                a:hover {
                  border-bottom-color: #00d4ff;
                }
              `
            }} />

            <div dangerouslySetInnerHTML={{ __html: docData.content }} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default LegalDocModal;