// 🔧 LegalDocModal.jsx - In-app legal document viewer (iOS Safari friendly)
import React from 'react';
import { X, ArrowLeft } from 'lucide-react';

const LegalDocModal = ({
  isOpen,
  onClose,
  docType = 'terms',
  uiLanguage = 'cs'
}) => {

  const getDocContent = (type) => {
    switch (type) {
      case 'terms':
        return {
          title: 'Terms of Service',
          lastUpdated: 'September 14, 2025',
          content: `
            <div class="important">
              <p><strong>Important:</strong> By using Omnia One AI, you agree to these terms. Please read them carefully before using our service.</p>
            </div>

            <h2>1. Acceptance of Terms</h2>
            <p>By accessing and using Omnia One AI ("the Service"), you accept and agree to be bound by the terms and provision of this agreement.</p>

            <h2>2. Description of Service</h2>
            <p>Omnia One AI is an artificial intelligence chat application that provides:</p>
            <ul>
              <li>AI-powered conversations using multiple models (Claude, GPT-4, Gemini)</li>
              <li>Voice interaction capabilities</li>
              <li>Document processing and analysis</li>
              <li>Multi-language support</li>
              <li>File upload and processing features</li>
            </ul>

            <h2>3. AI Service Limitations</h2>
            <div class="note">
              <p><strong>AI Disclaimer:</strong> Our AI responses are generated by machine learning models and may contain inaccuracies, biases, or outdated information. Always verify important information from authoritative sources.</p>
            </div>

            <p>You acknowledge that:</p>
            <ul>
              <li>AI responses are not professional advice (medical, legal, financial, etc.)</li>
              <li>The service may occasionally generate incorrect or inappropriate content</li>
              <li>We do not guarantee the accuracy or completeness of AI responses</li>
              <li>You use AI-generated content at your own risk</li>
            </ul>

            <h2>4. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul>
              <li>Use the service lawfully and responsibly</li>
              <li>Not attempt to exploit, harm, or reverse-engineer the service</li>
              <li>Not share harmful, illegal, or inappropriate content</li>
              <li>Respect intellectual property rights</li>
              <li>Not use the service for automated/bulk requests without permission</li>
            </ul>

            <h2>5. Data and Privacy</h2>
            <p>Your privacy is important to us:</p>
            <ul>
              <li>Chat conversations are stored locally in your browser</li>
              <li>We process your data as described in our Privacy Policy</li>
              <li>Files you upload are processed for AI analysis</li>
              <li>We implement security measures to protect your data</li>
            </ul>

            <h2>6. Prohibited Uses</h2>
            <p>You may NOT use Omnia One AI to:</p>
            <ul>
              <li>Generate harmful, illegal, or malicious content</li>
              <li>Harass, threaten, or harm others</li>
              <li>Violate any laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Attempt to circumvent service limitations</li>
              <li>Create or distribute malware, viruses, or harmful code</li>
            </ul>

            <h2>7. Service Availability</h2>
            <p>We strive to provide reliable service but cannot guarantee:</p>
            <ul>
              <li>100% uptime or availability</li>
              <li>Uninterrupted access to all features</li>
              <li>That the service will be error-free</li>
            </ul>

            <h2>8. Intellectual Property</h2>
            <p>The Omnia One AI service, including its design, code, and features, is owned by us and protected by intellectual property laws. You retain ownership of content you create, but grant us permission to process it for service delivery.</p>

            <h2>9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.</p>

            <h2>10. Account Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time through the settings.</p>

            <h2>11. Changes to Terms</h2>
            <p>We may update these terms periodically. Significant changes will be communicated through the service. Continued use constitutes acceptance of updated terms.</p>

            <h2>12. Governing Law</h2>
            <p>These terms are governed by applicable laws. Any disputes will be resolved through appropriate legal channels.</p>

            <h2>13. Contact Information</h2>
            <p>If you have questions about these Terms of Service, please contact us through the support channels available in the application.</p>

            <div class="note">
              <p><strong>Remember:</strong> These terms are designed to ensure a safe and positive experience for all users. By using Omnia One AI responsibly, you help us maintain a great service for everyone.</p>
            </div>
          `
        };

      case 'privacy':
        return {
          title: 'Privacy Policy',
          lastUpdated: 'September 14, 2025',
          content: `
            <div class="important">
              <p><strong>Important:</strong> This privacy policy explains how we collect, use, and protect your information when using Omnia One AI.</p>
            </div>

            <h2>Coming Soon</h2>
            <p>Privacy Policy content will be available soon. For now, please refer to our third-party AI providers' privacy policies:</p>
            <ul>
              <li><a href="https://www.anthropic.com/privacy" target="_blank">Anthropic Privacy Policy</a></li>
              <li><a href="https://openai.com/privacy/" target="_blank">OpenAI Privacy Policy</a></li>
              <li><a href="https://policies.google.com/privacy" target="_blank">Google Privacy Policy</a></li>
            </ul>
          `
        };

      default:
        return {
          title: 'Legal Document',
          lastUpdated: 'September 14, 2025',
          content: '<p>Document content coming soon...</p>'
        };
    }
  };

  const docData = getDocContent(docType);

  if (!isOpen) return null;

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        zIndex: 99999, // Higher than AboutModal
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        animation: 'fadeIn 0.2s ease',
        // iOS Safe area support
        paddingTop: 'env(safe-area-inset-top)',
        paddingBottom: 'env(safe-area-inset-bottom)',
        paddingLeft: 'env(safe-area-inset-left)',
        paddingRight: 'env(safe-area-inset-right)'
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      {/* MODAL CONTENT */}
      <div
        style={{
          width: '100vw',
          height: '100vh',
          background: 'linear-gradient(135deg, rgba(0, 4, 40, 0.98), rgba(0, 78, 146, 0.95))',
          backdropFilter: 'blur(20px)',
          WebkitBackdropFilter: 'blur(20px)',
          display: 'flex',
          flexDirection: 'column',
          animation: 'slideUp 0.3s ease-out',
          position: 'relative',
          overflow: 'hidden'
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* HEADER - Fixed Top */}
        <div style={{
          padding: '1rem 1.5rem',
          paddingTop: `max(1rem, calc(env(safe-area-inset-top) + 0.5rem))`,
          borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: 'rgba(0, 0, 0, 0.5)',
          backdropFilter: 'blur(20px)',
          WebkitBackdropFilter: 'blur(20px)',
          position: 'sticky',
          top: 0,
          zIndex: 1000
        }}>
          <button
            onClick={onClose}
            style={{
              background: 'rgba(255, 255, 255, 0.1)',
              border: '1px solid rgba(255, 255, 255, 0.2)',
              color: 'rgba(255, 255, 255, 0.9)',
              cursor: 'pointer',
              outline: 'none',
              WebkitTapHighlightColor: 'transparent',
              padding: '0.75rem 1rem',
              borderRadius: '12px',
              transition: 'all 0.2s ease',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              fontSize: '0.9rem',
              fontWeight: '600',
              backdropFilter: 'blur(10px)',
              WebkitBackdropFilter: 'blur(10px)',
              boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)'
            }}
            onMouseEnter={(e) => {
              e.target.style.backgroundColor = 'rgba(255, 255, 255, 0.15)';
              e.target.style.borderColor = 'rgba(255, 255, 255, 0.3)';
              e.target.style.color = 'white';
            }}
            onMouseLeave={(e) => {
              e.target.style.backgroundColor = 'rgba(255, 255, 255, 0.1)';
              e.target.style.borderColor = 'rgba(255, 255, 255, 0.2)';
              e.target.style.color = 'rgba(255, 255, 255, 0.9)';
            }}
          >
            <ArrowLeft size={18} />
            Back
          </button>

          <div style={{
            textAlign: 'center',
            flex: 1,
            margin: '0 1rem'
          }}>
            <div style={{
              color: 'white',
              fontSize: '1.1rem',
              fontWeight: 'bold'
            }}>
              {docData.title}
            </div>
            <div style={{
              color: 'rgba(255, 255, 255, 0.6)',
              fontSize: '0.8rem'
            }}>
              Last updated: {docData.lastUpdated}
            </div>
          </div>

          <button
            onClick={onClose}
            style={{
              background: 'rgba(255, 255, 255, 0.1)',
              border: '1px solid rgba(255, 255, 255, 0.2)',
              color: 'rgba(255, 255, 255, 0.9)',
              cursor: 'pointer',
              outline: 'none',
              WebkitTapHighlightColor: 'transparent',
              padding: '0.75rem',
              borderRadius: '12px',
              transition: 'all 0.2s ease',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              backdropFilter: 'blur(10px)',
              WebkitBackdropFilter: 'blur(10px)',
              boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)'
            }}
            onMouseEnter={(e) => {
              e.target.style.backgroundColor = 'rgba(255, 255, 255, 0.15)';
              e.target.style.borderColor = 'rgba(255, 255, 255, 0.3)';
              e.target.style.color = 'white';
            }}
            onMouseLeave={(e) => {
              e.target.style.backgroundColor = 'rgba(255, 255, 255, 0.1)';
              e.target.style.borderColor = 'rgba(255, 255, 255, 0.2)';
              e.target.style.color = 'rgba(255, 255, 255, 0.9)';
            }}
          >
            <X size={20} />
          </button>
        </div>

        {/* SCROLLABLE CONTENT */}
        <div style={{
          flex: 1,
          padding: '2rem',
          overflowY: 'auto',
          WebkitOverflowScrolling: 'touch'
        }}>
          <div style={{
            maxWidth: '800px',
            margin: '0 auto',
            fontSize: '0.9rem',
            lineHeight: '1.6',
            color: 'rgba(255, 255, 255, 0.9)'
          }}>
            <style dangerouslySetInnerHTML={{
              __html: `
                .important {
                  background: rgba(220, 38, 38, 0.1);
                  border: 1px solid rgba(220, 38, 38, 0.3);
                  border-radius: 8px;
                  padding: 1rem;
                  margin: 1.5rem 0;
                }

                .note {
                  background: rgba(59, 130, 246, 0.1);
                  border: 1px solid rgba(59, 130, 246, 0.3);
                  border-radius: 8px;
                  padding: 1rem;
                  margin: 1.5rem 0;
                }

                h2 {
                  font-size: 1.3rem;
                  font-weight: 600;
                  margin: 2rem 0 1rem 0;
                  color: #00d4ff;
                }

                h3 {
                  font-size: 1.1rem;
                  font-weight: 500;
                  margin: 1.5rem 0 0.5rem 0;
                  color: #8c52ff;
                }

                p {
                  margin-bottom: 1rem;
                  color: rgba(255, 255, 255, 0.9);
                }

                ul, ol {
                  margin: 1rem 0 1rem 2rem;
                }

                li {
                  margin-bottom: 0.5rem;
                  color: rgba(255, 255, 255, 0.9);
                }

                a {
                  color: #00d4ff;
                  text-decoration: none;
                  border-bottom: 1px solid transparent;
                  transition: border-color 0.2s ease;
                }

                a:hover {
                  border-bottom-color: #00d4ff;
                }
              `
            }} />

            <div dangerouslySetInnerHTML={{ __html: docData.content }} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default LegalDocModal;